### ISSUE TITLE
Doesn't work with no errors

### ISSUE THREAD

**Issue by bebsworthy** [kamranahmedse/git-pending#3]
Doesn't seem to work with no errors.

Here's a sample output

```
me@computer:~/projects/bigone$ git pending --oneline
Finding comments ..
Lookup completed ..
Reading authors ..
boyd@computer:~/projects/bigone$ grep -nr FIXME *
modules/app-test/src/main/kotlin/acme/test/StoreTestingValues.kt:381:            // FIXME: Find solution to fbUserId unicity when loading fake data
modules/app-test/src/main/kotlin/acme/test/StoreTestingValues.kt:512:        // FIXME 
[... skipped thousands of lines...]     
```

Let me know if you want any information.

**Comment by kamranahmedse** [comment]
Can you please provide the output for the below command
```bash
git grep -n -z -E -i '(TESTME)|(DOCME)|(FIXME)|(TODO)' HEAD
```
Also, is the project possibly opensource?

**Comment by bebsworthy** [comment]
Sorry it's closed. It's a huge repo with binary and js compiled file thrown in. Might be a reason. Some of the matches are huge. One of the match is a 1.3M character single line file. 

```
Binary file HEAD:bin/openapi-generator-cli-3.3.4.jar matches
Binary file HEAD:bin/openapi-generator-cli-4.0.1-SNAPSHOT.jar matches
HEAD:modules/admin/notes/todo.md^@2^@# TODO
HEAD:modules/admin/src/lang/index.ts^@4^@// TODO: element ui locale is not importable in ts
HEAD:modules/admin/src/main.ts^@127^@  // TODO: Check if access is authorized
HEAD:modules/admin/src/store/ability.ts^@18^@// TODO: this should be returned by the server
HEAD:modules/admin/src/views/Home.vue^@691^@      /* TODO: make this dynamic */
HEAD:modules/admin/src/views/Home.vue^@692^@      /* TODO: handle collapse of sidebar */
HEAD:modules/ui-comp/dist/js/app.905b8ef7.js.map:{"version":3,"sources":["webpack:///webpack/bootstrap","webpack:///./src/components/Chat.vue?9caa","webpack:///./src/App.vue?926f","webpack:///./src/App.vue?ee84","webpack:///./src/components/Chat.vue?f1dc","webpack:///./src/components/Input.vue?53a8","webpack:///./src/components/date.ts","webpack:///./src/components/type.ts","webpack:///./src/components/InputFilePicker.vue?5ba4","webpack:///./src/components/MessageText.vue?29c5","webpack:///./src/components/MessageInfo.vue?0d34","webpack: ...... [...SNIP 1.3 million characters....]
```

**Comment by scottfwalter** [comment]
@kamranahmedse it doesn't work for me either. I only see
```
Finding comments ..
Lookup completed ..
Reading authors ..
```

I've run your command:  git grep -n -z -E -i '(TESTME)|(DOCME)|(FIXME)|(TODO)' HEAD
and it does produce output

```
HEAD:src/initScript.js^@10^@//@fixme Hello World
HEAD:src/initScript.js^@22^@//TODO: in case of error loading configuration file, show an error message
HEAD:src/less/main.less^@244^@ * TODO: In a later version of this boilerplate, I'd like to automate this.
HEAD:src/less/modal-slider.less^@1^@//@todo. this modal slider should be global, move it to slider.less
```

This looks like it would be a very useful tool.  Hopefully you can get this issue resolved.  Let me know if you need anymore details.

**Comment by scottfwalter** [comment]
@kamranahmedse Perhaps this helps

```
git pending --debug
Finding comments ..
Lookup completed ..
Reading authors ..
Error: non-zero exit code 128

fatal: -L invalid line number: -1

    at ChildProcess.<anonymous> (/Users/scottwalter/.nvm/versions/node/v8.12.0/lib/node_modules/git-pending/node_modules/spawn-to-readstream/index.js:34:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
```

**Comment by scottfwalter** [comment]
@kamranahmedse  I believe I found the issue as git-grep isn't behaving with binary files.   In my case the repo has font files in it.   I looked at the repo for git-grep (which hasn't been updated in 5 years) and it doesn't provide a way to pass the "-I" option to ignore binary files.
